//! Service abstractions for dependency injection.
//!
//! This module provides trait-based abstractions for external dependencies,
//! enabling comprehensive testing without real I/O operations.
//!
//! # Architecture
//!
//! Each service has:
//! - A trait defining the interface
//! - A "Real" implementation for production use
//! - A mock implementation via mockall (in test builds)
//!
//! The `Services` struct aggregates all services.
//!
//! # Usage
//!
//! Production code receives `&Services` and calls methods on the traits.
//! Tests can inject mock implementations via `TestServicesBuilder`.

mod clock;
pub mod completion;
mod emitter;
mod fs;
mod git;
mod http;
mod process;
mod pty;
pub mod pty_osc;
mod reaper;
pub mod sandbox;
pub mod shell_integration;

pub use clock::{Clock, RealClock};
pub use completion::{
    CompletionRequest, CompletionResponse, CompletionService, DispatchingCompletionService,
    OutputFormat,
};
pub use emitter::EventEmitter;
pub use fs::{FileSystem, RealFileSystem};
pub use git::{GitClient, GitOutput, RealGitClient};
pub use http::{HttpClient, HttpConfig, HttpResponse, RealHttpClient};
pub use process::{
    ChildProcess, CommandOutput, KillOnDrop, ProcessSpawner, RealChildProcess, RealProcessSpawner,
    SpawnConfig,
};
pub use pty::{
    ensure_submitted_line, get_default_shell, read_pty_loop, scan_for_phrase, update_output_buffer,
    CommandState, LeaseTerminalBinding, PhraseScan, PortableTerminalChild, PtyComponents,
    PtyFactory, PtyPair, PtyResult, PtySession, PtyState, RealPtyFactory, RemoteTerminalChild,
    TerminalChild, TerminalOutputWatcher, MAX_BUFFER_SIZE, PHRASE_EXCERPT_MAX,
};
pub use pty_osc::{Osc133Event, Osc133Parser};
pub use reaper::{OsProcessReaper, ProcessReaper};
pub use sandbox::SandboxPolicy;
pub use shell_integration::{apply_shell_integration, integration_dir};

use std::sync::Arc;

/// Container for all injectable services.
///
/// This struct holds trait objects for each service, enabling
/// dependency injection for both production and test use.
#[derive(Clone)]
pub struct Services {
    pub process: Arc<dyn ProcessSpawner>,
    pub git: Arc<dyn GitClient>,
    pub http: Arc<dyn HttpClient>,
    pub emitter: Arc<dyn EventEmitter>,
    pub clock: Arc<dyn Clock>,
    pub fs: Arc<dyn FileSystem>,
    pub pty_factory: Arc<dyn PtyFactory>,
    pub completion: Arc<dyn CompletionService>,
    pub reaper: Arc<dyn ProcessReaper>,
}

#[cfg(any(test, feature = "test-utils"))]
pub mod testing {
    //! Test utilities for service mocking.
    //!
    //! Re-exports mock types generated by mockall and custom mocks.

    pub use super::clock::MockClock;
    pub use super::completion::MockCompletionService;
    pub use super::emitter::{CapturingEmitter, MockEventEmitter};
    pub use super::fs::MockFileSystem;
    pub use super::git::MockGitClient;
    pub use super::http::MockHttpClient;
    pub use super::process::{MockChildProcess, MockProcessSpawner, RecordingProcessSpawner};
    pub use super::pty::MockPtyFactory;
    pub use super::reaper::RecordingReaper;

    use super::*;

    macro_rules! service_setter {
        ($name:ident, $field:ident, $trait:path, $arg:ident) => {
            #[doc = concat!("Set a custom ", stringify!($trait), " implementation.")]
            pub fn $name<S: $trait + 'static>(mut self, $arg: S) -> Self {
                self.$field = Some(Arc::new($arg));
                self
            }
        };
    }

    /// Builder for creating test Services with mock implementations.
    ///
    /// # Example
    ///
    /// ```ignore
    /// let mut clock = MockClock::new();
    /// clock.expect_now().returning(|| 1234567890);
    ///
    /// let services = TestServicesBuilder::new()
    ///     .with_clock(clock)
    ///     .build();
    ///
    /// assert_eq!(services.clock.now(), 1234567890);
    /// ```
    pub struct TestServicesBuilder {
        clock: Option<Arc<dyn Clock>>,
        completion: Option<Arc<dyn CompletionService>>,
        fs: Option<Arc<dyn FileSystem>>,
        git: Option<Arc<dyn GitClient>>,
        http: Option<Arc<dyn HttpClient>>,
        process: Option<Arc<dyn ProcessSpawner>>,
        emitter: Option<Arc<dyn EventEmitter>>,
        pty_factory: Option<Arc<dyn PtyFactory>>,
        reaper: Option<Arc<dyn ProcessReaper>>,
    }

    impl TestServicesBuilder {
        pub fn new() -> Self {
            Self {
                clock: None,
                completion: None,
                fs: None,
                git: None,
                http: None,
                process: None,
                emitter: None,
                pty_factory: None,
                reaper: None,
            }
        }

        service_setter!(with_completion, completion, CompletionService, completion);
        service_setter!(with_clock, clock, Clock, clock);
        service_setter!(with_fs, fs, FileSystem, fs);
        service_setter!(with_git, git, GitClient, git);
        service_setter!(with_http, http, HttpClient, http);
        service_setter!(with_process, process, ProcessSpawner, process);
        service_setter!(with_emitter, emitter, EventEmitter, emitter);
        service_setter!(with_pty_factory, pty_factory, PtyFactory, pty_factory);
        service_setter!(with_reaper, reaper, ProcessReaper, reaper);

        /// Build the Services with mocks for any unspecified services.
        ///
        /// Unspecified services get default mock implementations that
        /// return empty/success values.
        pub fn build(self) -> Services {
            let process_arc = self.process.unwrap_or_else(|| {
                let mock = MockProcessSpawner::new();
                Arc::new(mock)
            });

            Services {
                completion: self.completion.unwrap_or_else(|| {
                    let mock = MockCompletionService::new();
                    Arc::new(mock)
                }),
                clock: self.clock.unwrap_or_else(|| {
                    let mut mock = MockClock::new();
                    mock.expect_now().returning(|| 0);
                    mock.expect_now_u64().returning(|| 0);
                    Arc::new(mock)
                }),
                fs: self.fs.unwrap_or_else(|| {
                    let mock = MockFileSystem::new();
                    Arc::new(mock)
                }),
                git: self.git.unwrap_or_else(|| {
                    let mock = MockGitClient::new();
                    Arc::new(mock)
                }),
                http: self.http.unwrap_or_else(|| {
                    let mock = MockHttpClient::new();
                    Arc::new(mock)
                }),
                process: process_arc,
                emitter: self
                    .emitter
                    .unwrap_or_else(|| Arc::new(CapturingEmitter::new())),
                pty_factory: self.pty_factory.unwrap_or_else(|| {
                    let mock = MockPtyFactory::new();
                    Arc::new(mock)
                }),
                reaper: self
                    .reaper
                    .unwrap_or_else(|| Arc::new(RecordingReaper::new())),
            }
        }
    }

    impl Default for TestServicesBuilder {
        fn default() -> Self {
            Self::new()
        }
    }
}
