//! Service abstractions for dependency injection.
//!
//! This module provides trait-based abstractions for external dependencies,
//! enabling comprehensive testing without real I/O operations.
//!
//! # Architecture
//!
//! Each service has:
//! - A trait defining the interface
//! - A "Real" implementation for production use
//! - A mock implementation via mockall (in test builds)
//!
//! The `Services` struct aggregates all services.
//!
//! # Usage
//!
//! Production code receives `&Services` and calls methods on the traits.
//! Tests can inject mock implementations via `TestServicesBuilder`.

mod clock;
pub mod completion;
mod emitter;
mod fs;
mod git;
mod http;
mod process;
mod pty;

pub use clock::{Clock, RealClock};
pub use completion::{
    CompletionRequest, CompletionResponse, CompletionService, DispatchingCompletionService,
    OutputFormat,
};
pub use emitter::EventEmitter;
pub use fs::{FileSystem, RealFileSystem};
pub use git::{GitClient, GitOutput, RealGitClient};
pub use http::{HttpClient, HttpConfig, HttpResponse, RealHttpClient};
pub use process::{
    ChildProcess, CommandOutput, ProcessSpawner, RealChildProcess, RealProcessSpawner, SpawnConfig,
};
pub use pty::{
    get_default_shell, read_pty_loop, update_output_buffer, PtyComponents, PtyFactory, PtyPair,
    PtyResult, PtySession, PtyState, RealPtyFactory, MAX_BUFFER_SIZE,
};

use std::sync::Arc;

/// Container for all injectable services.
///
/// This struct holds trait objects for each service, enabling
/// dependency injection for both production and test use.
#[derive(Clone)]
pub struct Services {
    pub process: Arc<dyn ProcessSpawner>,
    pub git: Arc<dyn GitClient>,
    pub http: Arc<dyn HttpClient>,
    pub emitter: Arc<dyn EventEmitter>,
    pub clock: Arc<dyn Clock>,
    pub fs: Arc<dyn FileSystem>,
    pub pty_factory: Arc<dyn PtyFactory>,
    pub completion: Arc<dyn CompletionService>,
}

#[cfg(any(test, feature = "test-utils"))]
pub mod testing {
    //! Test utilities for service mocking.
    //!
    //! Re-exports mock types generated by mockall and custom mocks.

    pub use super::clock::MockClock;
    pub use super::completion::MockCompletionService;
    pub use super::emitter::{CapturingEmitter, MockEventEmitter};
    pub use super::fs::MockFileSystem;
    pub use super::git::MockGitClient;
    pub use super::http::MockHttpClient;
    pub use super::process::{MockChildProcess, MockProcessSpawner};
    pub use super::pty::MockPtyFactory;

    use super::*;

    /// Builder for creating test Services with mock implementations.
    ///
    /// # Example
    ///
    /// ```ignore
    /// let mut clock = MockClock::new();
    /// clock.expect_now().returning(|| 1234567890);
    ///
    /// let services = TestServicesBuilder::new()
    ///     .with_clock(clock)
    ///     .build();
    ///
    /// assert_eq!(services.clock.now(), 1234567890);
    /// ```
    pub struct TestServicesBuilder {
        clock: Option<Arc<dyn Clock>>,
        completion: Option<Arc<dyn CompletionService>>,
        fs: Option<Arc<dyn FileSystem>>,
        git: Option<Arc<dyn GitClient>>,
        http: Option<Arc<dyn HttpClient>>,
        process: Option<Arc<dyn ProcessSpawner>>,
        emitter: Option<Arc<dyn EventEmitter>>,
        pty_factory: Option<Arc<dyn PtyFactory>>,
    }

    impl TestServicesBuilder {
        pub fn new() -> Self {
            Self {
                clock: None,
                completion: None,
                fs: None,
                git: None,
                http: None,
                process: None,
                emitter: None,
                pty_factory: None,
            }
        }

        /// Set a custom CompletionService implementation.
        pub fn with_completion<C: CompletionService + 'static>(mut self, completion: C) -> Self {
            self.completion = Some(Arc::new(completion));
            self
        }

        /// Set a custom Clock implementation.
        pub fn with_clock<C: Clock + 'static>(mut self, clock: C) -> Self {
            self.clock = Some(Arc::new(clock));
            self
        }

        /// Set a custom FileSystem implementation.
        pub fn with_fs<F: FileSystem + 'static>(mut self, fs: F) -> Self {
            self.fs = Some(Arc::new(fs));
            self
        }

        /// Set a custom GitClient implementation.
        pub fn with_git<G: GitClient + 'static>(mut self, git: G) -> Self {
            self.git = Some(Arc::new(git));
            self
        }

        /// Set a custom HttpClient implementation.
        pub fn with_http<H: HttpClient + 'static>(mut self, http: H) -> Self {
            self.http = Some(Arc::new(http));
            self
        }

        /// Set a custom ProcessSpawner implementation.
        pub fn with_process<P: ProcessSpawner + 'static>(mut self, process: P) -> Self {
            self.process = Some(Arc::new(process));
            self
        }

        /// Set a custom EventEmitter implementation.
        pub fn with_emitter<E: EventEmitter + 'static>(mut self, emitter: E) -> Self {
            self.emitter = Some(Arc::new(emitter));
            self
        }

        /// Set a custom PtyFactory implementation.
        pub fn with_pty_factory<P: PtyFactory + 'static>(mut self, pty_factory: P) -> Self {
            self.pty_factory = Some(Arc::new(pty_factory));
            self
        }

        /// Build the Services with mocks for any unspecified services.
        ///
        /// Unspecified services get default mock implementations that
        /// return empty/success values.
        pub fn build(self) -> Services {
            let process_arc = self.process.unwrap_or_else(|| {
                let mock = MockProcessSpawner::new();
                Arc::new(mock)
            });

            Services {
                completion: self.completion.unwrap_or_else(|| {
                    let mock = MockCompletionService::new();
                    Arc::new(mock)
                }),
                clock: self.clock.unwrap_or_else(|| {
                    let mut mock = MockClock::new();
                    mock.expect_now().returning(|| 0);
                    mock.expect_now_u64().returning(|| 0);
                    Arc::new(mock)
                }),
                fs: self.fs.unwrap_or_else(|| {
                    let mock = MockFileSystem::new();
                    Arc::new(mock)
                }),
                git: self.git.unwrap_or_else(|| {
                    let mock = MockGitClient::new();
                    Arc::new(mock)
                }),
                http: self.http.unwrap_or_else(|| {
                    let mock = MockHttpClient::new();
                    Arc::new(mock)
                }),
                process: process_arc,
                emitter: self
                    .emitter
                    .unwrap_or_else(|| Arc::new(CapturingEmitter::new())),
                pty_factory: self.pty_factory.unwrap_or_else(|| {
                    let mock = MockPtyFactory::new();
                    Arc::new(mock)
                }),
            }
        }
    }

    impl Default for TestServicesBuilder {
        fn default() -> Self {
            Self::new()
        }
    }
}
