//! Memory db-layer tests for the Canon v2 node-scoped memory model.

use crate::common;

use std::sync::Arc;

use cairn_core::memories::{commands, db};
use cairn_core::models::{CreateMemory, MemoryScope, MemoryStatus};
use cairn_db::turso::params;
use serde_json::json;

async fn seed_node(
    local_db: &cairn_core::internal::storage::LocalDb,
    project_key: &str,
    issue_number: i64,
    exec_seq: i64,
    node_segment: &str,
) -> (String, String) {
    let project_id = common::create_project(local_db, project_key).await;
    let issue_id = format!("issue-{project_key}-{issue_number}");
    let execution_id = format!("exec-{project_key}-{exec_seq}");
    let job_id = format!("job-{project_key}-{node_segment}");
    local_db
        .execute_script(&format!(
            "\
            INSERT INTO issues(id, project_id, number, title, status, created_at, updated_at)\
             VALUES ('{issue_id}', '{project_id}', {issue_number}, 'Memory issue', 'active', 1, 1);\
            INSERT INTO executions(id, recipe_id, issue_id, project_id, status, started_at, seq)\
             VALUES ('{execution_id}', 'recipe', '{issue_id}', '{project_id}', 'running', 1, {exec_seq});\
            INSERT INTO jobs(id, execution_id, issue_id, project_id, recipe_node_id, node_name, uri_segment, status, created_at, updated_at)\
             VALUES ('{job_id}', '{execution_id}', '{issue_id}', '{project_id}', '{node_segment}', '{node_segment}', '{node_segment}', 'running', 1, 1);"
        ))
        .await
        .unwrap();
    (project_id, job_id)
}

async fn create_node_memory(
    local_db: &cairn_core::internal::storage::LocalDb,
    id: &str,
    name: &str,
    content: &str,
    project_id: &str,
    job_id: &str,
    node_seq: i64,
) -> cairn_core::models::Memory {
    db::create_memory(
        local_db,
        id,
        Some(name),
        content,
        Some(project_id),
        "project",
        project_id,
        Some(job_id),
        Some(node_seq),
        Some("cairn://p/CAIRN/1/1/builder/chat/turn/3"),
    )
    .await
    .unwrap()
}

#[tokio::test]
async fn create_and_load_node_memory() {
    let (_temp, local_db) = common::migrated_db().await;
    let (project_id, job_id) = seed_node(&local_db, "MEM", 1, 1, "builder").await;

    let memory = create_node_memory(
        &local_db,
        "memory-1",
        "tests-before-push",
        "Always run tests before pushing",
        &project_id,
        &job_id,
        1,
    )
    .await;

    assert_eq!(memory.id, "memory-1");
    assert_eq!(memory.name.as_deref(), Some("tests-before-push"));
    assert_eq!(memory.content, "Always run tests before pushing");
    assert_eq!(memory.project_id.as_deref(), Some(project_id.as_str()));
    assert_eq!(memory.status, MemoryStatus::Draft);
    assert_eq!(memory.scope, MemoryScope::Project);
    assert_eq!(memory.scope_value, project_id);
    assert_eq!(memory.job_id.as_deref(), Some(job_id.as_str()));
    assert_eq!(memory.node_seq, Some(1));
    assert_eq!(
        memory.provenance_uri.as_deref(),
        Some("cairn://p/CAIRN/1/1/builder/chat/turn/3")
    );

    let loaded = db::load_memory(&local_db, "memory-1").await.unwrap();
    assert_eq!(loaded.content, memory.content);
}

#[tokio::test]
async fn command_create_uses_uuid_and_keeps_name_display_only() {
    let (_temp, local_db) = common::migrated_db().await;
    let (_project_id, job_id) = seed_node(&local_db, "UUID", 1, 1, "builder").await;

    let input = CreateMemory {
        name: Some("Diesel schema is autogenerated".to_string()),
        content: "edit the migration files instead".to_string(),
        project_id: None,
        scope: MemoryScope::Workspace,
        scope_value: "workspace".to_string(),
        job_id: Some(job_id.clone()),
        node_seq: Some(1),
        provenance_uri: None,
    };

    let first = commands::create(&local_db, input.clone()).await.unwrap();
    let second = commands::create(
        &local_db,
        CreateMemory {
            node_seq: Some(2),
            ..input
        },
    )
    .await
    .unwrap();

    assert_ne!(first.id, "diesel-schema-is-autogenerated");
    assert_ne!(second.id, "diesel-schema-is-autogenerated-2");
    assert_ne!(first.id, second.id);
    assert_eq!(
        first.name.as_deref(),
        Some("Diesel schema is autogenerated")
    );
}

#[tokio::test]
async fn command_create_allows_missing_name() {
    let (_temp, local_db) = common::migrated_db().await;
    let (_project_id, job_id) = seed_node(&local_db, "NONAME", 1, 1, "builder").await;

    let memory = commands::create(
        &local_db,
        CreateMemory {
            name: None,
            content: "Nameless memory content".to_string(),
            project_id: None,
            scope: MemoryScope::Workspace,
            scope_value: "workspace".to_string(),
            job_id: Some(job_id),
            node_seq: Some(1),
            provenance_uri: None,
        },
    )
    .await
    .unwrap();

    assert_eq!(memory.name, None);
    let loaded = db::load_memory(&local_db, &memory.id).await.unwrap();
    assert_eq!(loaded.name, None);
}

#[tokio::test]
async fn append_creates_draft_memory_with_only_content_and_reads_by_uri() {
    let (temp, local_db) = common::migrated_db().await;
    seed_node(&local_db, "APP", 1, 1, "builder").await;
    let db = Arc::new(local_db);
    let orch = common::orchestrator(&temp, db.clone());

    let report = common::change_resource(
        &orch,
        json!([{
            "target": "cairn://p/APP/1/1/builder/memories",
            "mode": "append",
            "payload": { "content": "Append-only content" }
        }]),
    )
    .await;
    let report: serde_json::Value = serde_json::from_str(&report).unwrap();
    assert_eq!(
        report["failures"].as_array().map(Vec::len).unwrap_or(0),
        0,
        "{report:?}"
    );
    assert_eq!(report["applied"].as_array().unwrap().len(), 1, "{report:?}");

    let memory_id = db::resolve_node_memory_id(&db, "APP", 1, 1, "builder", 1)
        .await
        .unwrap()
        .expect("memory URI should resolve");
    let memory = db::load_memory(&db, &memory_id).await.unwrap();
    assert_eq!(memory.name, None);
    assert_eq!(memory.content, "Append-only content");
    assert_eq!(memory.status, MemoryStatus::Draft);
    assert_eq!(memory.scope, MemoryScope::Project);

    let uri = "cairn://p/APP/1/1/builder/memories/1";
    let rendered = common::read_resource(&orch, uri).await;
    assert!(rendered.contains("# Memory `cairn://p/APP/1/1/builder/memories/1`"));
    assert!(rendered.contains("Append-only content"));
}

#[tokio::test]
async fn append_role_memory_scopes_by_agent_role_not_node_name() {
    let (temp, local_db) = common::migrated_db().await;
    // A project whose repo defines the `builder` role canon, so the role home
    // resolves to this project (and the memory's project_id FK is satisfied).
    let repo = temp.path().join("repo");
    std::fs::create_dir_all(repo.join(".cairn/agents")).unwrap();
    std::fs::write(
        repo.join(".cairn/agents/builder.md"),
        "Builder role prompt.",
    )
    .unwrap();
    let project_id = common::insert_project_with_repo(&local_db, "ROLE", &repo).await;

    // The recipe node segment is `agent-1`, but it runs the `builder` role.
    local_db
        .execute_script(&format!(
            "\
            INSERT INTO issues(id, project_id, number, title, status, created_at, updated_at)\
             VALUES ('issue-ROLE', '{project_id}', 1, 'Memory issue', 'active', 1, 1);\
            INSERT INTO executions(id, recipe_id, issue_id, project_id, status, started_at, seq)\
             VALUES ('exec-ROLE', 'recipe', 'issue-ROLE', '{project_id}', 'running', 1, 1);\
            INSERT INTO jobs(id, execution_id, issue_id, project_id, recipe_node_id, node_name, uri_segment, agent_config_id, status, created_at, updated_at)\
             VALUES ('job-ROLE', 'exec-ROLE', 'issue-ROLE', '{project_id}', 'agent-1', 'agent-1', 'agent-1', 'builder', 'running', 1, 1);"
        ))
        .await
        .unwrap();
    let db = Arc::new(local_db);
    let orch = common::orchestrator(&temp, db.clone());

    let report = common::change_resource(
        &orch,
        json!([{
            "target": "cairn://p/ROLE/1/1/agent-1/memories",
            "mode": "append",
            "payload": { "content": "Role-scoped insight", "scope": "role" }
        }]),
    )
    .await;
    let report: serde_json::Value = serde_json::from_str(&report).unwrap();
    assert_eq!(
        report["failures"].as_array().map(Vec::len).unwrap_or(0),
        0,
        "{report:?}"
    );

    let memory_id = db::resolve_node_memory_id(&db, "ROLE", 1, 1, "agent-1", 1)
        .await
        .unwrap()
        .expect("memory URI should resolve");
    let memory = db::load_memory(&db, &memory_id).await.unwrap();
    assert_eq!(memory.scope, MemoryScope::Role);
    assert_eq!(
        memory.scope_value, "builder",
        "role memory must key on the agent role, not the recipe node name"
    );
}

#[tokio::test]
async fn node_memories_affordance_advertises_append_with_optional_name() {
    let (temp, local_db) = common::migrated_db().await;
    seed_node(&local_db, "AFF", 1, 1, "builder").await;
    let db = Arc::new(local_db);
    let orch = common::orchestrator(&temp, db);

    let rendered = common::read_resource(&orch, "cairn://p/AFF/1/1/builder/memories").await;
    assert!(
        rendered.contains("mode:\"append\"") || rendered.contains("mode=append"),
        "{rendered}"
    );
    assert!(rendered.contains("required `content"), "{rendered}");
    assert!(rendered.contains("optional `name"), "{rendered}");
    assert!(!rendered.contains("mode=\"create\""), "{rendered}");
}

#[tokio::test]
async fn node_memory_sequence_confirms_and_resolves_uri() {
    let (_temp, local_db) = common::migrated_db().await;
    let (project_id, job_id) = seed_node(&local_db, "SEQ", 7, 3, "builder").await;

    let first = create_node_memory(
        &local_db,
        "first",
        "Role fact",
        "Builder should use the node memories target",
        &project_id,
        &job_id,
        1,
    )
    .await;
    let second = create_node_memory(
        &local_db,
        "second",
        "Workspace fact",
        "Workspace scoped content",
        &project_id,
        &job_id,
        2,
    )
    .await;

    assert_eq!(
        db::next_node_memory_seq(&local_db, &job_id).await.unwrap(),
        3
    );

    let uri = db::build_node_memory_uri_for_memory(&local_db, &first)
        .await
        .unwrap();
    assert_eq!(uri, "cairn://p/SEQ/7/3/builder/memories/1");
    let resolved = db::resolve_node_memory_id(&local_db, "SEQ", 7, 3, "builder", 1)
        .await
        .unwrap();
    assert_eq!(resolved.as_deref(), Some("first"));

    let drafts = db::load_draft_memories_for_job(&local_db, &job_id)
        .await
        .unwrap();
    assert_eq!(drafts.len(), 2);

    // Since #2141, `confirm_draft_memories_for_job` advances a job's drafts out
    // of `draft` only once the owning issue is merged (drafts stay inert until
    // the work lands). Mark the seeded issue merged so this test exercises the
    // confirm path it asserts.
    local_db
        .execute(
            "UPDATE issues SET merged_at = 1 WHERE id = 'issue-SEQ-7'",
            (),
        )
        .await
        .unwrap();

    let confirmed = db::confirm_draft_memories_for_job(&local_db, &job_id)
        .await
        .unwrap();
    assert_eq!(confirmed.len(), 2);
    assert_eq!(
        db::load_memory(&local_db, &first.id).await.unwrap().status,
        MemoryStatus::Pending
    );
    assert_eq!(
        db::load_memory(&local_db, &second.id).await.unwrap().status,
        MemoryStatus::Pending
    );
}

#[tokio::test]
async fn update_and_delete_memory_by_internal_id() {
    let (_temp, local_db) = common::migrated_db().await;
    let (project_id, job_id) = seed_node(&local_db, "UPD", 1, 1, "builder").await;
    create_node_memory(&local_db, "m", "name", "original", &project_id, &job_id, 1).await;

    let updated = db::update_memory(&local_db, "m", Some("revised content"), Some("claimed"))
        .await
        .unwrap();

    assert_eq!(updated.content, "revised content");
    assert_eq!(updated.status, MemoryStatus::Claimed);

    db::delete_memory(&local_db, "m").await.unwrap();
    assert!(db::load_memory(&local_db, "m").await.is_err());
}

#[tokio::test]
async fn load_all_memories_scopes_by_project() {
    let (_temp, local_db) = common::migrated_db().await;
    let (project_a, job_a) = seed_node(&local_db, "AAA", 1, 1, "builder").await;
    let (project_b, job_b) = seed_node(&local_db, "BBB", 1, 1, "builder").await;
    let (_workspace_project, workspace_job) = seed_node(&local_db, "WKS", 1, 1, "builder").await;
    local_db
        .execute(
            "INSERT OR IGNORE INTO projects(id, workspace_id, name, key, repo_path, created_at, updated_at, is_workspace)\
             VALUES ('workspace', 'default', 'Workspace', 'WORKSPACE', '/tmp/workspace', 1, 1, 1)",
            (),
        )
        .await
        .unwrap();

    create_node_memory(
        &local_db,
        "ws",
        "workspace",
        "workspace fact",
        "workspace",
        &workspace_job,
        1,
    )
    .await;
    create_node_memory(&local_db, "a", "a", "project A fact", &project_a, &job_a, 1).await;
    create_node_memory(&local_db, "b", "b", "project B fact", &project_b, &job_b, 1).await;

    let scoped = db::load_all_memories(&local_db, Some(&project_a))
        .await
        .unwrap();
    let ids: Vec<&str> = scoped.iter().map(|m| m.id.as_str()).collect();
    assert!(ids.contains(&"ws"));
    assert!(ids.contains(&"a"));
    assert!(!ids.contains(&"b"));

    let workspace = db::load_all_memories(&local_db, Some("workspace"))
        .await
        .unwrap();
    let ids: Vec<&str> = workspace.iter().map(|m| m.id.as_str()).collect();
    assert_eq!(ids, vec!["ws"]);
}

#[tokio::test]
async fn similar_memory_neighbors_use_node_uris() {
    let (_temp, local_db) = common::migrated_db().await;
    let (project_id, job_id) = seed_node(&local_db, "SIM", 1, 1, "builder").await;
    let query = create_node_memory(
        &local_db,
        "query",
        "query",
        "query",
        &project_id,
        &job_id,
        1,
    )
    .await;
    let neighbor = create_node_memory(
        &local_db,
        "neighbor",
        "neighbor",
        "neighbor",
        &project_id,
        &job_id,
        2,
    )
    .await;
    let query_uri = db::build_node_memory_uri_for_memory(&local_db, &query)
        .await
        .unwrap();
    let neighbor_uri = db::build_node_memory_uri_for_memory(&local_db, &neighbor)
        .await
        .unwrap();

    let vector = vec![1.0_f32, 0.0, 0.0];
    let bytes = cairn_core::internal::embeddings::vector::to_bytes(&vector);
    for uri in [&query_uri, &neighbor_uri] {
        local_db
            .execute(
                "INSERT INTO resource_embeddings(uri, embedding, model, dims, created_at, updated_at)\
                 VALUES (?1, ?2, 'test', 3, 1, 1)",
                params![uri.as_str(), bytes.clone()],
            )
            .await
            .unwrap();
    }

    let neighbors = db::similar_memory_neighbors(&local_db, &query, &query_uri, &[], 0.1, 5)
        .await
        .unwrap();
    assert_eq!(neighbors.len(), 1);
    assert_eq!(neighbors[0].memory.id, "neighbor");
    assert_eq!(neighbors[0].uri, "cairn://p/SIM/1/1/builder/memories/2");
}
