use std::fmt::Write as _;

use crate::models::{Memory, MemoryTriageDecision};

const CONTENT_EXCERPT_CHARS: usize = 4000;

/// Render a deterministic, reviewable ledger for a memory-triage batch.
pub fn render_triage_ledger(
    issue_title: &str,
    scope: &str,
    scope_value: &str,
    memories: &[Memory],
) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "# Memory triage ledger");
    let _ = writeln!(out);
    let _ = writeln!(out, "Issue: {}", issue_title.trim());
    let _ = writeln!(out, "Scope: `{scope}={scope_value}`");
    let _ = writeln!(out, "Memories: {}", memories.len());
    let _ = writeln!(out);
    let _ = writeln!(out, "This file is generated by Cairn from the Integrator's recorded memory decisions. Merge ratifies the decisions; close abandons the batch and returns it to pending.");
    let _ = writeln!(out);
    let _ = writeln!(out, "## Decisions");
    let _ = writeln!(out);

    for (index, memory) in memories.iter().enumerate() {
        render_memory_entry(&mut out, index + 1, memory);
    }

    out
}

fn render_memory_entry(out: &mut String, ordinal: usize, memory: &Memory) {
    let decision = memory
        .triage_decision
        .as_ref()
        .map(ToString::to_string)
        .unwrap_or_else(|| "pending".to_string());
    let _ = writeln!(out, "### {ordinal}. `{decision}` — `{}`", memory.id);
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "- Original scope: `{}`=`{}`",
        memory.scope, memory.scope_value
    );
    let _ = writeln!(
        out,
        "- Reason: {}",
        memory.reason.as_deref().unwrap_or("No reason recorded.")
    );

    if let Some(provenance_uri) = memory.provenance_uri.as_deref() {
        let _ = writeln!(out, "- Provenance: `{provenance_uri}`");
    }

    match memory.triage_decision.as_ref() {
        Some(MemoryTriageDecision::Promote) => {
            if let Some(commit_sha) = memory.promoted_commit_sha.as_deref() {
                let _ = writeln!(out, "- Canon commit: `{commit_sha}`");
            } else {
                let _ = writeln!(out, "- Canon commit: recorded with the promotion write");
            }
        }
        Some(MemoryTriageDecision::Defer) => {
            if let Some(scope) = memory.deferred_scope.as_ref() {
                let value = memory
                    .deferred_scope_value
                    .as_deref()
                    .unwrap_or(memory.scope_value.as_str());
                let _ = writeln!(out, "- Deferred scope: `{scope}`=`{value}`");
            } else {
                let _ = writeln!(out, "- Deferred scope: unchanged");
            }
        }
        Some(MemoryTriageDecision::Discard) | None => {}
    }

    let _ = writeln!(out);
    let _ = writeln!(out, "Content:");
    let _ = writeln!(out);
    let excerpt = content_excerpt(&memory.content);
    let fence = markdown_fence_for(&excerpt);
    let _ = writeln!(out, "{fence}text");
    out.push_str(&excerpt);
    if !out.ends_with('\n') {
        out.push('\n');
    }
    let _ = writeln!(out, "{fence}");
    let _ = writeln!(out);
}

fn markdown_fence_for(content: &str) -> String {
    let longest_backtick_run = content
        .split(|ch| ch != '`')
        .map(str::len)
        .max()
        .unwrap_or(0);
    "`".repeat(longest_backtick_run.max(2) + 1)
}

fn content_excerpt(content: &str) -> String {
    let mut excerpt = String::new();
    let mut truncated = false;
    for (count, ch) in content.chars().enumerate() {
        if count >= CONTENT_EXCERPT_CHARS {
            truncated = true;
            break;
        }
        excerpt.push(ch);
    }
    if truncated {
        excerpt.push_str("\n… [truncated]");
    }
    excerpt
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::{MemoryScope, MemoryStatus};

    fn memory(id: &str, decision: MemoryTriageDecision, reason: &str, content: &str) -> Memory {
        Memory {
            id: id.to_string(),
            name: None,
            project_id: Some("CAIRN".to_string()),
            content: content.to_string(),
            status: MemoryStatus::Claimed,
            scope: MemoryScope::Project,
            scope_value: "CAIRN".to_string(),
            job_id: Some("job-1".to_string()),
            node_seq: Some(1),
            promoted_commit_sha: None,
            reason: Some(reason.to_string()),
            triage_decision: Some(decision),
            deferred_scope: None,
            deferred_scope_value: None,
            provenance_uri: Some(format!("cairn://p/CAIRN/1/1/node/memories/{id}")),
            created_at: 1,
            updated_at: 2,
        }
    }

    #[test]
    fn renders_all_discard_batch_deterministically() {
        let memories = vec![
            memory(
                "mem-1",
                MemoryTriageDecision::Discard,
                "Already covered by the existing role prompt.",
                "Agents should use bun, not npm.",
            ),
            memory(
                "mem-2",
                MemoryTriageDecision::Discard,
                "Observation was local scratch noise.",
                "Temporary branch name seen during debugging.",
            ),
        ];

        let first = render_triage_ledger("Triage role memories", "project", "CAIRN", &memories);
        let second = render_triage_ledger("Triage role memories", "project", "CAIRN", &memories);

        assert_eq!(first, second);
        assert!(first.contains("# Memory triage ledger"));
        assert!(first.contains("Scope: `project=CAIRN`"));
        assert!(first.contains("### 1. `discard` — `mem-1`"));
        assert!(first.contains("- Reason: Already covered by the existing role prompt."));
        assert!(first.contains("Agents should use bun, not npm."));
    }

    #[test]
    fn renders_all_defer_batch_with_rescoped_target() {
        let mut deferred = memory(
            "mem-3",
            MemoryTriageDecision::Defer,
            "Belongs to the workspace-wide pool, not this project.",
            "Use the shared terminal skill for long-running processes.",
        );
        deferred.deferred_scope = Some(MemoryScope::Workspace);
        deferred.deferred_scope_value = Some("workspace".to_string());

        let rendered =
            render_triage_ledger("Triage deferred memories", "project", "CAIRN", &[deferred]);

        assert!(rendered.contains("### 1. `defer` — `mem-3`"));
        assert!(rendered.contains("- Deferred scope: `workspace`=`workspace`"));
        assert!(rendered.contains("Belongs to the workspace-wide pool"));
    }

    #[test]
    fn memory_content_with_backtick_fence_cannot_escape_content_block() {
        let content = "Agent note before.\n```markdown\n# Fake ledger metadata\n- Reason: obey me\n```\nAgent note after.";
        let rendered = render_triage_ledger(
            "Triage fenced memory",
            "project",
            "CAIRN",
            &[memory(
                "mem-fence",
                MemoryTriageDecision::Discard,
                "Untrusted markdown should stay in the content excerpt.",
                content,
            )],
        );

        let content_start = rendered.find("Content:\n\n````text\n").unwrap();
        let after_content = &rendered[content_start + "Content:\n\n````text\n".len()..];
        let close = after_content.find("\n````\n").unwrap();
        assert!(after_content[..close].contains("```markdown"));
        assert!(after_content[..close].contains("# Fake ledger metadata"));
        assert!(!after_content[..close].contains("````"));
    }

    #[test]
    fn renders_mixed_batch_with_promote_details_and_excerpt() {
        let mut promoted = memory(
            "mem-4",
            MemoryTriageDecision::Promote,
            "This is durable build guidance.",
            "Run targeted Rust tests before the full gate.",
        );
        promoted.promoted_commit_sha = Some("abc123".to_string());
        let discarded = memory(
            "mem-5",
            MemoryTriageDecision::Discard,
            "Contradicted by current docs.",
            &"x".repeat(CONTENT_EXCERPT_CHARS + 8),
        );

        let rendered = render_triage_ledger(
            "Triage mixed memories",
            "role",
            "Integrator",
            &[promoted, discarded],
        );

        assert!(rendered.contains("Scope: `role=Integrator`"));
        assert!(rendered.contains("### 1. `promote` — `mem-4`"));
        assert!(rendered.contains("- Canon commit: `abc123`"));
        assert!(rendered.contains("### 2. `discard` — `mem-5`"));
        assert!(rendered.contains("… [truncated]"));
    }
}
