//! Purging ephemeral copies and rebuilding derived ones from sources that have
//! already been withheld.
//!
//! # Ordering is the whole mechanism
//!
//! A derived store is rebuilt *after* its sources are quarantined, and that
//! ordering is what makes the rebuild sanitized. Nothing here scrubs anything:
//! the search index and the embeddings are regenerated by reading the transcript
//! through the same gate every other reader goes through, and that gate now
//! substitutes a withholding notice. So the rebuilt index contains the notice,
//! because the notice is what the transcript now says.
//!
//! Rebuilding first, or scrubbing during the rebuild, would both be worse. The
//! first regenerates the disclosure. The second adds a second definition of
//! "sanitized" that has to stay in step with the first one forever.
//!
//! # Purge versus rebuild
//!
//! An ephemeral store is purged rather than rebuilt because there is nothing to
//! rebuild it from and nothing lost: a dropped check-result row means the check
//! re-runs, and a dropped stream chunk was already folded into its event. The
//! purge is targeted at the rows that matched, which is why ephemeral stores are
//! scanned even though their handling is unconditional — see [`super::sink`].

use cairn_db::storage::LocalDb;

use super::inventory::AffectedRecord;
use super::sink::{Gate, SinkKind};

fn now() -> i64 {
    chrono::Utc::now().timestamp()
}

/// What the rebuild phase did.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Rebuilt {
    /// Ephemeral rows deleted.
    pub purged: usize,
    /// Derived rows dropped so they regenerate from the withheld sources.
    pub invalidated: usize,
    /// Stores that were rebuilt, for the audit record.
    pub sinks: Vec<&'static str>,
}

/// Purge the ephemeral records that matched.
///
/// Targeted at `records`, so a disclosure confined to one check's output does
/// not cost the machine its entire check cache.
pub async fn purge_ephemeral(db: &LocalDb, records: &[AffectedRecord]) -> usize {
    let mut purged = 0;
    for record in records {
        purged += match record.sink {
            // Every project and environment that cached this check's output
            // holds the same text, so the hash is the right key.
            SinkKind::CheckResultCache => {
                drop_rows(
                    db,
                    "DELETE FROM check_result_cache WHERE input_hash = ?1",
                    &record.locator,
                )
                .await
            }
            SinkKind::StreamChunk => {
                drop_rows(
                    db,
                    "DELETE FROM message_stream_chunks WHERE id = ?1",
                    &record.locator,
                )
                .await
            }
            // Every other store is a source or derived one, handled elsewhere.
            _ => 0,
        };
    }
    purged
}

/// Drop the derived rows covering the affected sources, so they regenerate from
/// the withheld transcript.
///
/// Scoped to the events that were actually affected rather than the whole store.
/// A full reindex of every project is an expensive way to reach the same state,
/// and an incident response that takes an hour is one an operator interrupts.
/// Never fails. A rebuild is the last and least urgent step of a response, and
/// letting it abort one would discard the containment that already happened — an
/// embedding table that could not be cleared is a far smaller problem than a
/// quarantine that was rolled back because of it. Failures are logged and
/// reported as an incomplete rebuild.
pub async fn rebuild_derived(db: &LocalDb, records: &[AffectedRecord]) -> Rebuilt {
    let event_ids: Vec<&str> = records
        .iter()
        .filter(|record| record.sink == SinkKind::TranscriptEvent)
        .map(|record| record.locator.as_str())
        .collect();

    let mut invalidated = 0;
    let mut sinks = Vec::new();

    // Vibes are computed from `events.data`, and a turn's embedding from the
    // events in it. Dropping the row makes the worker recompute it, and what it
    // will read through the gate is the withholding notice.
    let mut embeddings_cleared = 0;
    for event_id in &event_ids {
        embeddings_cleared +=
            drop_rows(db, "DELETE FROM event_vibes WHERE event_id = ?1", event_id).await;
        embeddings_cleared += drop_rows(
            db,
            "DELETE FROM turn_embeddings WHERE turn_id IN \
             (SELECT turn_id FROM events WHERE id = ?1 AND turn_id IS NOT NULL)",
            event_id,
        )
        .await;
    }
    if embeddings_cleared > 0 {
        invalidated += embeddings_cleared;
        sinks.push(SinkKind::Embedding.as_str());
    }

    // The full-text index is fed by `search_outbox`; enqueueing an affected row
    // is how a reindex is asked for everywhere else in the tree, so this uses
    // the same door rather than reaching into Tantivy directly.
    let reindexed = enqueue_search_repair(db, records).await;
    if reindexed > 0 {
        invalidated += reindexed;
        sinks.push(SinkKind::SearchIndex.as_str());
    }

    Rebuilt {
        purged: 0,
        invalidated,
        sinks,
    }
}

async fn drop_rows(db: &LocalDb, sql: &str, key: &str) -> usize {
    match db.execute(sql, (key,)).await {
        Ok(count) => count as usize,
        Err(error) => {
            log::warn!("disclosure response could not clear a derived row for {key}: {error}");
            0
        }
    }
}

/// Repair the full-text index for every affected searchable record.
///
/// # Reindex or evict, decided by the source's gate
///
/// Reindexing is only sanitizing when the source it re-reads answers with the
/// withholding notice. That holds for a transcript event, whose read gate
/// substitutes the notice, so an `upsert` genuinely replaces the indexed
/// document with clean text.
///
/// It does not hold for a message, an issue body, or an artifact. Those stores
/// have no read gate, so the indexer would re-read the original plaintext and
/// write the credential straight back into Tantivy — taking a stale copy of the
/// disclosure and *refreshing* it, which is worse than having done nothing.
///
/// So an ungated source's indexed document is deleted instead. The index is a
/// derived store: deleting a document destroys no information, it only makes
/// the record unfindable by search until an operator repairs the source and it
/// is reindexed normally. Given the choice between a searchable credential and
/// an unsearchable record, the record loses.
async fn enqueue_search_repair(db: &LocalDb, records: &[AffectedRecord]) -> usize {
    let mut queued = 0;
    for record in records {
        // `content_type` is the index's own vocabulary, set by the triggers that
        // normally feed this table. Matching it is what makes a hand-enqueued
        // row indistinguishable from a triggered one.
        let (source_table, content_type) = match record.sink {
            SinkKind::TranscriptEvent => ("events", "event"),
            SinkKind::Message => ("messages", "message"),
            SinkKind::IssueBody => ("issues", "issue"),
            SinkKind::Artifact => ("artifacts", "artifact"),
            _ => continue,
        };
        let op = match record.sink.gate() {
            Gate::Withholds => "upsert",
            Gate::Reports(_) => "delete",
        };
        match db
            .execute(
                "INSERT INTO search_outbox \
                 (id, source_table, source_id, content_type, op, status, created_at) \
                 VALUES (?1, ?2, ?3, ?4, ?5, 'pending', ?6)",
                (
                    uuid::Uuid::new_v4().to_string(),
                    source_table,
                    record.locator.as_str(),
                    content_type,
                    op,
                    now(),
                ),
            )
            .await
        {
            Ok(count) => queued += count as usize,
            Err(error) => log::warn!(
                "disclosure response could not queue a search {op} for {} {}: {error}",
                record.sink,
                record.locator
            ),
        }
    }
    queued
}
